version:  2.1

orbs:
  codecov: codecov/codecov@1.1.1

jobs:
  build:
    working_directory: ~/Jeopardy
    docker:
      # running an image of android 10
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: CHMOD permissions
          command: chmod +x ./gradlew
      - run:
          # Export base64 encoded google-services.json
          # into local bash variables
          name: Export Google Services Json
          command: echo 'export GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON"' >> $BASH_ENV
      - run:
          # Decode the base64 string
          name: Decode Google Services Json
          command: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
      - run:
          name: Run unit test
          command: ./gradlew testDebugUnitTest
      - run:
          name: Generate code coverage
          command: ./gradlew jacocoTestReportdebug
      - codecov/upload:
          # Upload coverage to codecov
          flags: unittest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master # filters to only work on main
